/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carnegametest222222;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author JustClick
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    private List<Player> playerList = new ArrayList<>();
    public homePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGame = new javax.swing.JButton();
        playerAmount = new javax.swing.JTextField();
        playerName1 = new javax.swing.JTextField();
        inputImage1 = new javax.swing.JLabel();
        inputImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startGame.setBackground(new java.awt.Color(0, 102, 255));
        startGame.setForeground(new java.awt.Color(255, 0, 51));
        startGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letsgobutton.png"))); // NOI18N
        startGame.setBorder(null);
        startGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });
        getContentPane().add(startGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 150, 50));

        playerAmount.setOpaque(false);
        playerAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerAmountActionPerformed(evt);
            }
        });
        playerAmount.setVisible(true);
        getContentPane().add(playerAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 200, 30));

        playerName1.setOpaque(false);
        playerName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerName1ActionPerformed(evt);
            }
        });
        playerAmount.setVisible(true);
        getContentPane().add(playerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 200, 30));

        inputImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inputfield.png"))); // NOI18N
        getContentPane().add(inputImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inputImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inputfield.png"))); // NOI18N
        getContentPane().add(inputImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginshapewithouthinput.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerAmountActionPerformed

    private void playerName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerName1ActionPerformed

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
         String playerName = playerName1.getText();
    int amount = Integer.parseInt(playerAmount.getText());
    
    theGame gamePage = new theGame(playerName, amount);
    gamePage.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_startGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inputImage;
    private javax.swing.JLabel inputImage1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField playerAmount;
    private javax.swing.JTextField playerName1;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
