/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carnegametest222222;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
/**
 *
 * @author JustClick
 */

public class theEnd extends javax.swing.JFrame {
       private List<LabelInfoData> labelDataList;
    /**
     * Creates new form theEnd
     */

  
       
    public theEnd(Crane carne,List<LabelInfoData> labelDataList) {
        initComponents();
          
           this.labelDataList = labelDataList;
   
           
             printLabelDataList();
             
//             if (carne.getBoxArea5() != null) {
//            System.out.println("BoxArea5 Y: " + carne.getBoxArea5().getY());
//            System.out.println("BoxArea5 X: " + carne.getBoxArea5().getX());
//        } else {
//            System.out.println("BoxArea5 is null");
//        }
//
//        if (carne.getBoxArea4() != null) {
//            System.out.println("BoxArea4 Y: " + carne.getBoxArea4().getY());
//            System.out.println("BoxArea4 X: " + carne.getBoxArea4().getX());
//        } else {
//            System.out.println("BoxArea4 is null");
//        }
    }
public void printLabelDataList() {
    if (labelDataList.isEmpty()) {
        endBoard.setText("Game Over - good change next time");
    } else {
        StringBuilder labelText = new StringBuilder("<html>");

        for (LabelInfoData labelInfoData : labelDataList) {
            labelText.append("Prize Name: ").append(labelInfoData.getLabelName()).append(" ");
            labelText.append("Mass: ").append(labelInfoData.getMass()).append("<br>");
            labelText.append("Value: ").append(labelInfoData.getValue()).append(" ");
            labelText.append("Total Value: ").append(labelInfoData.getTotal()).append("<br>");
            labelText.append("-------------<br>");
        }

        labelText.append("</html>");
        endBoard.setText(labelText.toString());
    }
}


    
    
//       public void printLabelDataList() {
//        for (LabelInfoData labelInfoData : labelDataList) {
//              System.out.println("from the end");
//            System.out.println("Label Name: " + labelInfoData.getLabelName());
//            System.out.println("Mass: " + labelInfoData.getMass());
//            System.out.println("Value: " + labelInfoData.getValue());
//            System.out.println("Total: " + labelInfoData.getTotal());
//            System.out.println("-------------");
//        
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endBoard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endBoard.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        endBoard.setForeground(new java.awt.Color(255, 255, 255));
        endBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/game/theEnd.png"))); // NOI18N
        endBoard.setText("<html><center>Game Over<br>Good chance next time</center></html>");
        endBoard.setToolTipText("");
        endBoard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(endBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                          new theEnd(new Crane(), new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endBoard;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
